name: Prerelease

on:
  pull_request:
    # paths:
    #   - 'fdm-core/**'
    #   - 'fdm-data/**'
    branches:
      - main

# concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 9
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Create snapshot versions and publish them
        id: changesets
        uses: changesets/action@v1
        with:
          version: changeset version --snapshot ${{ github.head_ref }
          publish: pnpm prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}